# Generated by Django 3.1.6 on 2021-02-21 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitrusAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='Author', max_length=100)),
                ('author_id', models.CharField(max_length=200)),
                ('host', models.CharField(default='http://localhost:8000/', max_length=200)),
                ('display_name', models.CharField(default='http://localhost:8000/author/<django.db.models.fields.CharField>', max_length=300)),
                ('github', models.CharField(default='', max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
